<?php
/**
 * Generate spamhaus_drop_data.php from the Spamhaus combined DROP list.
 *
 * Reads the DROP feed as NDJSON on stdin (one JSON object per line, e.g.
 *   {"cidr":"1.10.16.0/20","sblid":"SBL256894","rir":"apnic"}
 * plus a trailing {"type":"metadata",...} line with no "cidr"), converts each
 * CIDR to an inclusive [start_int, end_int] unsigned-32-bit IPv4 range, sorts
 * ascending by start, merges overlapping/adjacent ranges, and writes a complete,
 * machine-owned PHP data file to stdout.
 *
 * Usage (also what .github/workflows/sync-spamhaus-drop.yml runs):
 *   curl -sf https://www.spamhaus.org/drop/drop_v4.json \
 *     | php scripts/gen-spamhaus-drop.php > spamhaus_drop_data.php
 *
 * Exit non-zero (without emitting a file) on empty/garbage input so a failed
 * Spamhaus fetch never empties the committed data file. The lookup that consumes
 * this output is ip_in_spamhaus_drop() in report_functions.php.
 */

/**
 * Parse the DROP NDJSON into a list of un-merged per-CIDR records, each
 * [start_int, end_int, "cidr"], sorted ascending by start. Pulled out as a pure
 * function so both the merged hot-path array and the report's per-CIDR labels are
 * derived from one parse, and so it can be unit-tested without I/O.
 *
 * @param string $ndjson  Raw NDJSON feed contents.
 * @return array<int, array{0:int,1:int,2:string}>  Sorted original CIDR records.
 */
function spamhaus_drop_cidrs_from_ndjson(string $ndjson): array {
    $cidrs = [];
    foreach (explode("\n", $ndjson) as $line) {
        $line = trim($line);
        if ($line === '') {
            continue;
        }
        $rec = json_decode($line, true);
        // Skip the metadata header/footer line and anything without a cidr.
        if (!is_array($rec) || !isset($rec['cidr']) || !is_string($rec['cidr'])) {
            continue;
        }
        $cidr = $rec['cidr'];
        if (strpos($cidr, '/') === false) {
            continue;
        }
        [$net, $prefix] = explode('/', $cidr, 2);
        $prefix = (int) $prefix;
        $base   = ip2long($net);
        if ($base === false || $prefix < 0 || $prefix > 32) {
            continue; // not a valid IPv4 CIDR (DROPv6 is out of scope)
        }
        // Unsigned base via %u; 64-bit PHP holds the full 0..2^32-1 range.
        $start = (int) sprintf('%u', $base);
        $size  = 1 << (32 - $prefix);            // /0 => 2^32, fits in 64-bit int
        $end   = $start + $size - 1;
        $cidrs[] = [$start, $end, $cidr];
    }

    // Sort ascending by start (then by end so a containing block precedes the
    // blocks it covers — handy for the report's most-specific-on-overlap search).
    usort($cidrs, static fn($a, $b) => $a[0] <=> $b[0] ?: $a[1] <=> $b[1]);

    return $cidrs;
}

/**
 * Parse the DROP NDJSON into a sorted, merged list of [start, end] int ranges.
 * Pulled out as a pure function so it can be unit-tested without I/O.
 *
 * @param string $ndjson  Raw NDJSON feed contents.
 * @return array<int, array{0:int,1:int}>  Sorted, merged inclusive ranges.
 */
function spamhaus_drop_ranges_from_ndjson(string $ndjson): array {
    $cidrs = spamhaus_drop_cidrs_from_ndjson($ndjson);
    if (!$cidrs) {
        return [];
    }

    // Already sorted ascending by start; merge overlapping or adjacent ranges so
    // the consumer's binary search can assume a disjoint, sorted list.
    $merged = [];
    [$curStart, $curEnd] = $cidrs[0];
    $count = count($cidrs);
    for ($i = 1; $i < $count; $i++) {
        [$s, $e] = $cidrs[$i];
        if ($s <= $curEnd + 1) {            // overlapping or directly adjacent
            if ($e > $curEnd) {
                $curEnd = $e;
            }
        } else {
            $merged[] = [$curStart, $curEnd];
            $curStart = $s;
            $curEnd   = $e;
        }
    }
    $merged[] = [$curStart, $curEnd];

    return $merged;
}

/**
 * Render the data file body from the merged ranges + the un-merged CIDR list.
 *
 * Emits two globals: $spamhaus_drop_ranges (merged, the hot-path membership
 * array — byte-identical to the pre-CIDR-array format) and $spamhaus_drop_cidrs
 * (the original per-CIDR records, so the report can name + block the specific
 * netblock the merge threw away).
 *
 * @param array<int, array{0:int,1:int}>        $ranges  Merged inclusive ranges.
 * @param array<int, array{0:int,1:int,string}> $cidrs   Un-merged [start,end,cidr].
 */
function spamhaus_drop_render(array $ranges, array $cidrs): string {
    $today = gmdate('Y-m-d');
    $out  = "<?php\n";
    $out .= "// AUTO-GENERATED by .github/workflows/sync-spamhaus-drop.yml — do not hand-edit.\n";
    $out .= "// Source: https://www.spamhaus.org/drop/drop_v4.json (combined DROP, includes former EDROP)\n";
    $out .= "// Terms:  https://www.spamhaus.org/drop/terms/  (c) The Spamhaus Project SLU\n";
    $out .= "// Last sync: {$today}\n";
    $out .= "//\n";
    $out .= "// Sorted ascending by start_int, non-overlapping (merged on generation).\n";
    $out .= "// One [start_int, end_int] inclusive unsigned-32-bit IPv4 pair per listed CIDR.\n";
    $out .= "// Consumed by ip_in_spamhaus_drop() in report_functions.php (binary search).\n";
    $out .= "global \$spamhaus_drop_ranges;\n";
    $out .= "\$spamhaus_drop_ranges = [\n";
    foreach ($ranges as $r) {
        $out .= "    [{$r[0]}, {$r[1]}],\n";
    }
    $out .= "];\n";
    $out .= "\n";
    $out .= "// Un-merged original CIDRs as [start_int, end_int, \"cidr\"], sorted ascending by\n";
    $out .= "// start. The merge above throws away CIDR boundaries; the threat report needs to\n";
    $out .= "// name + block the specific netblock, so the originals are retained here.\n";
    $out .= "// Consumed by spamhaus_drop_cidr_for_ip() in report_functions.php (binary search).\n";
    $out .= "global \$spamhaus_drop_cidrs;\n";
    $out .= "\$spamhaus_drop_cidrs = [\n";
    foreach ($cidrs as $c) {
        $out .= "    [{$c[0]}, {$c[1]}, " . var_export($c[2], true) . "],\n";
    }
    $out .= "];\n";
    return $out;
}

// --- CLI entry point ---------------------------------------------------------
// Only run when executed directly (curl ... | php scripts/gen-spamhaus-drop.php).
// When required from the test suite this is skipped, so the functions above are
// importable without consuming STDIN.
if (PHP_SAPI === 'cli'
    && isset($_SERVER['SCRIPT_FILENAME'])
    && realpath($_SERVER['SCRIPT_FILENAME']) === realpath(__FILE__)
) {
    $ndjson = stream_get_contents(STDIN);
    if ($ndjson === false || trim($ndjson) === '') {
        fwrite(STDERR, "gen-spamhaus-drop: empty input — refusing to emit an empty data file.\n");
        exit(1);
    }

    $cidrs  = spamhaus_drop_cidrs_from_ndjson($ndjson);
    $ranges = spamhaus_drop_ranges_from_ndjson($ndjson);
    if (!$ranges) {
        fwrite(STDERR, "gen-spamhaus-drop: parsed 0 CIDR ranges — aborting (bad feed?).\n");
        exit(1);
    }

    fwrite(STDERR, 'gen-spamhaus-drop: ' . count($ranges) . ' merged ranges, '
        . count($cidrs) . " original CIDRs.\n");
    echo spamhaus_drop_render($ranges, $cidrs);
}
