#!/usr/bin/env bash
# Decide whether develop's Spamhaus data may be auto-promoted to main.
#
# Background: sync-spamhaus.yml and sync-spamhaus-drop.yml merge develop into
# main and deploy it to production with no human review whenever develop's only
# delta is the Spamhaus data. "Only touches the data file" is not enough: anyone
# who can push to develop could put PHP code inside that file. So before any
# merge the workflows run this script (from a trusted main checkout, never from
# develop) against the exact develop commit they will merge, and it accepts only
# the line shapes the generators produce.
#
# Usage:
#   validate-spamhaus-promote.sh asn  <main asn_classification.php> <develop asn_classification.php>
#   validate-spamhaus-promote.sh drop <develop spamhaus_drop_data.php>
#
# Exit codes:
#   0  promotable
#   1  develop content is not what the generator writes: do NOT promote, fail the job
#   2  (asn only) asn_classification.php differs from main outside the auto-sync
#      block, i.e. a hand edit that needs a normal release PR: do NOT promote
#   64 usage error

set -euo pipefail
export LC_ALL=C

ASN_BEGIN_MARKER="    // --- BEGIN AUTO-SYNC SPAMHAUS ASN-DROP (do not hand-edit) ---"
ASN_END_MARKER="    // --- END AUTO-SYNC SPAMHAUS ASN-DROP ---"

fail() {
    echo "validate-spamhaus-promote: $*" >&2
    exit 1
}

# Print lines of the file that do not match any of the given extended regexes
# (each anchored to the whole line), prefixed with their line numbers.
unexpected_lines() {
    local file=$1; shift
    local args=()
    for re in "$@"; do args+=(-e "$re"); done
    grep -nvxE "${args[@]}" "$file" || true
}

validate_asn() {
    local main_file=$1 dev_file=$2

    # Markers: exactly one of each, as whole lines, BEGIN before END.
    local n_begin n_end
    n_begin=$(grep -cxF -- "$ASN_BEGIN_MARKER" "$dev_file" || true)
    n_end=$(grep -cxF -- "$ASN_END_MARKER" "$dev_file" || true)
    [ "$n_begin" = 1 ] || fail "asn: expected exactly 1 BEGIN marker line, found $n_begin"
    [ "$n_end" = 1 ] || fail "asn: expected exactly 1 END marker line, found $n_end"
    local l_begin l_end
    l_begin=$(grep -nxF -- "$ASN_BEGIN_MARKER" "$dev_file" | cut -d: -f1)
    l_end=$(grep -nxF -- "$ASN_END_MARKER" "$dev_file" | cut -d: -f1)
    [ "$l_begin" -lt "$l_end" ] || fail "asn: END marker (line $l_end) comes before BEGIN marker (line $l_begin)"

    # Every line strictly between the markers is an ASN entry or one of the
    # fixed comment lines sync-spamhaus.yml writes.
    local block bad
    block=$(mktemp)
    sed -n "$((l_begin + 1)),$((l_end - 1))p" "$dev_file" > "$block"
    bad=$(unexpected_lines "$block" \
        "    'AS[0-9]{1,10}' => 'scanning'," \
        '    // Synced monthly from https://www\.spamhaus\.org/drop/asndrop\.json by' \
        '    // \.github/workflows/sync-spamhaus\.yml\. To override an entry'"'"'s classification,' \
        '    // move it OUT of this block into the appropriate manual section above\.' \
        '    // Last sync: [0-9]{4}-[0-9]{2}-[0-9]{2}')
    rm -f "$block"
    if [ -n "$bad" ]; then
        echo "validate-spamhaus-promote: asn: unexpected line(s) inside the auto-sync block (line numbers relative to the block):" >&2
        echo "$bad" | head -20 >&2
        exit 1
    fi

    # Outside the block the file must be byte-identical to main. Markers match
    # whole lines only, so a code line that merely contains marker text cannot
    # hide itself (or the lines after it) from this comparison.
    if ! cmp -s <(strip_asn_block < "$main_file") <(strip_asn_block < "$dev_file"); then
        echo "validate-spamhaus-promote: asn: asn_classification.php differs from main outside the auto-sync block." >&2
        exit 2
    fi
}

strip_asn_block() {
    awk -v b="$ASN_BEGIN_MARKER" -v e="$ASN_END_MARKER" '
        $0 == b { f = 1; next }
        $0 == e { f = 0; next }
        !f
    '
}

# spamhaus_drop_data.php is entirely generated by scripts/gen-spamhaus-drop.php
# (spamhaus_drop_render). Reduce the file to its shape: the date line becomes
# <DATE>, each run of data rows becomes one <RANGES> or <CIDRS> line, and every
# other line is kept verbatim behind a "|" (so a literal "<RANGES>" line in the
# file cannot pose as a placeholder). The shape must equal the generator's
# skeleton exactly. No free-form // lines are allowed anywhere: a "?>" inside a
# // comment ends the PHP block and turns the rest of the file into output.
DROP_SKELETON='<?php
// AUTO-GENERATED by .github/workflows/sync-spamhaus-drop.yml — do not hand-edit.
// Source: https://www.spamhaus.org/drop/drop_v4.json (combined DROP, includes former EDROP)
// Terms:  https://www.spamhaus.org/drop/terms/  (c) The Spamhaus Project SLU
<DATE>
//
// Sorted ascending by start_int, non-overlapping (merged on generation).
// One [start_int, end_int] inclusive unsigned-32-bit IPv4 pair per listed CIDR.
// Consumed by ip_in_spamhaus_drop() in report_functions.php (binary search).
global $spamhaus_drop_ranges;
$spamhaus_drop_ranges = [
<RANGES>
];

// Un-merged original CIDRs as [start_int, end_int, "cidr"], sorted ascending by
// start. The merge above throws away CIDR boundaries; the threat report needs to
// name + block the specific netblock, so the originals are retained here.
// Consumed by spamhaus_drop_cidr_for_ip() in report_functions.php (binary search).
global $spamhaus_drop_cidrs;
$spamhaus_drop_cidrs = [
<CIDRS>
];'

validate_drop() {
    local dev_file=$1

    # The generator always ends the file with a newline; anything after the last
    # newline would be invisible to the line-based check below.
    [ -s "$dev_file" ] || fail "drop: file is empty"
    [ "$(tail -c1 "$dev_file" | od -An -tx1 | tr -d ' ')" = 0a ] \
        || fail "drop: file does not end with a newline"

    local expected actual
    expected=$(mktemp)
    actual=$(mktemp)
    printf '%s\n' "$DROP_SKELETON" | sed -E '/^<(DATE|RANGES|CIDRS)>$/!s/^/|/' > "$expected"
    sed -E \
        -e 's/^/|/' \
        -e 's#^\|// Last sync: [0-9]{4}-[0-9]{2}-[0-9]{2}$#<DATE>#' \
        -e 's#^\|    \[[0-9]{1,10}, [0-9]{1,10}\],$#<RANGES>#' \
        -e "s#^\\|    \\[[0-9]{1,10}, [0-9]{1,10}, '[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}/[0-9]{1,2}'\\],\$#<CIDRS>#" \
        "$dev_file" \
        | awk '($0 == "<RANGES>" || $0 == "<CIDRS>") && $0 == prev { next } { print; prev = $0 }' \
        > "$actual"

    if ! cmp -s "$expected" "$actual"; then
        echo "validate-spamhaus-promote: drop: spamhaus_drop_data.php does not match the generator's output shape (< expected, > found):" >&2
        diff "$expected" "$actual" | head -20 >&2 || true
        rm -f "$expected" "$actual"
        exit 1
    fi
    rm -f "$expected" "$actual"
}

case "${1:-}" in
    asn)
        [ $# -eq 3 ] || { echo "usage: $0 asn <main-file> <develop-file>" >&2; exit 64; }
        validate_asn "$2" "$3"
        ;;
    drop)
        [ $# -eq 2 ] || { echo "usage: $0 drop <develop-file>" >&2; exit 64; }
        validate_drop "$2"
        ;;
    *)
        echo "usage: $0 asn <main-file> <develop-file> | drop <develop-file>" >&2
        exit 64
        ;;
esac

echo "validate-spamhaus-promote: $1: OK"
